### ISSUE TITLE
 Wrong format

### ISSUE THREAD

**Issue by nian-si** [arXiv/html_feedback#149]
### Description

It is new a wrong format for text in the math environment.

### (Required) What is this issue most closely related to? Select one.

Formula

### Internal issue ID

e6923bd8-16dd-416d-a3f3-98fce5d63e61

### Paper URL

https://browse.arxiv.org/html/2312.11823v1

### Browser

Chrome/120.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Does this issue request matching font-family in the main text and the math text (`<mtext>`) ?

If so, we could evaluate a CSS rule such as

```css
mtext {
    font-family: var(--text-font-family);
    font-weight: var(--text-font-weight);
}
```
